### ISSUE TITLE
Support encoding types

### ISSUE THREAD

**Issue by kyleconroy** [interagent/heroics#48]
This is an offshoot of #12, but if a `link` specifies an encoding type, the body should be encoded in the manner. For example, I'd like the body to be encoded as 'application/x-www-form-urlencoded'.

**Comment by geemus** [comment]
Interesting. Yeah, that sounds pretty reasonable. Would you be interested in working on a pull for this?

**Comment by kyleconroy** [comment]
Yep, just wanted to check to make sure you'd be okay with the change.

**Comment by geemus** [comment]
@kyleconroy Yeah, I think that is fine. In my usage I'm not sure I would use form encoded (I try to use json bodies where I can), but I could see it being helpful if you had an endpoint that accepted images or video or something. And just because I haven't had a use for it historically certainly doesn't invalidate it. I'm not super confident what it should look like/how it should fit within the schema. It trips once more upon the fact that json-schema doesn't provide an easy mechanism for defining stuff about headers. Rather than doing this as a one-off I have some sense that figuring out a reasonable way to do headers and nesting it there might be better, but I haven't given the headers part too much thought recently. Does that make sense? What do you think?

**Comment by kyleconroy** [comment]
Not sure what you mean. Hyper-schema specifically has the [encType](http://json-schema.org/latest/json-schema-hypermedia.html#anchor37) for this use case.

**Comment by geemus** [comment]
Ah, I guess I meant there isn't a generic way to refer to headers. Since I hadn't needed it, I didn't realize there were specific mechanisms for media type and encoding. Good catch! I'll review the pull presently.
